import ctypes


def get_screen_resolution() -> tuple[float, float]:
    ctypes.windll.user32.SetProcessDPIAware()
    width = ctypes.windll.user32.GetSystemMetrics(0)
    height = ctypes.windll.user32.GetSystemMetrics(1)
    return width, height


CURRENT_SCREEN_SIZE = get_screen_resolution()
GAME_FIELD_PROPORTIONS = float(16 / 9)

SCREEN_WIDTH = CURRENT_SCREEN_SIZE[0] * 0.8
SCREEN_HEIGHT = SCREEN_WIDTH / GAME_FIELD_PROPORTIONS

GAME_FIELD_WIDTH = SCREEN_WIDTH
GAME_FIELD_HEIGHT = GAME_FIELD_WIDTH / GAME_FIELD_PROPORTIONS


# Game consts
FPS = 120

BLOCK_SIZE = GAME_FIELD_WIDTH / 41

PLAYER_SPEED = BLOCK_SIZE / 5.5
PLAYER_JUMP_FORCE = BLOCK_SIZE / 4
PLAYER_HEALTH = 100

BIG_BULLET_WIDTH = BLOCK_SIZE / 2
BIG_BULLET_HEIGHT = BLOCK_SIZE / 3
BIG_BULLET_SPEED = BLOCK_SIZE / 3.0
BIG_BULLET_MAX_DISTANCE = GAME_FIELD_WIDTH * 2
BIG_BULLET_DAMAGE = 100

SMALL_BULLET_WIDTH = BLOCK_SIZE / 3
SMALL_BULLET_HEIGHT = BLOCK_SIZE / 4.5
SMALL_BULLET_SPEED = BLOCK_SIZE / 2
SMALL_BULLET_MAX_DISTANCE = GAME_FIELD_WIDTH * 1
SMALL_BULLET_DAMAGE = 34

ENEMY_SPEED = 1.7

MAX_ANTI_GRAVITY = BLOCK_SIZE / 700
CHANGE_ANTI_GRAVITY = 0.03

GRAVITY = BLOCK_SIZE / 115

IS_DEBUG = False

# Other

BUTTON_WIDTH = GAME_FIELD_WIDTH / 6
BUTTON_HEIGHT = GAME_FIELD_HEIGHT / 20
BUTTON_OFFSET = BUTTON_HEIGHT / 3

SCORES_WIDTH = BLOCK_SIZE
SCORES_HEIGHT = GAME_FIELD_HEIGHT / 25

VICTORY_TEXT_WIDTH = GAME_FIELD_WIDTH / 3
VICTORY_TEXT_HEIGHT = GAME_FIELD_HEIGHT / 7.5


# Colors
RED = (1, 0, 0)
GREEN = (0, 1, 0)
BLUE = (0, 0, 1)
WHITE = (1, 1, 1)
ORANGE = (1, 0.5, 0)
YELLOW = (1, 1, 0)
DARK_GREY = (0.2, 0.2, 0.2)
GREY = (0.21, 0.21, 0.21)
GREY_2 = (0.3, 0.3, 0.3)
BG_COLOR = (120 / 255, 120 / 255, 120 / 255)
