from engine.common import get_screen_resolution


# Screen & Game Field sizes
CURRENT_SCREEN_SIZE = get_screen_resolution()
GAME_FIELD_PROPORTIONS = float(16 / 9)

SCREEN_WIDTH = CURRENT_SCREEN_SIZE[0] * 0.8
SCREEN_HEIGHT = SCREEN_WIDTH / GAME_FIELD_PROPORTIONS

GAME_FIELD_WIDTH = SCREEN_WIDTH
GAME_FIELD_HEIGHT = GAME_FIELD_WIDTH / GAME_FIELD_PROPORTIONS


# Game consts / FPS
MENU_FPS = 60

UPDATE_FPS = 120
DRAW_FPS = 60

UPDATE_DT = 1.0 / UPDATE_FPS
DRAW_DT = 1.0 / DRAW_FPS

OLD_FPS = 120

# Game consts / Characteristics
MAP_WIDTH = 41
MAP_HEIGHT = int(GAME_FIELD_HEIGHT / (GAME_FIELD_WIDTH / MAP_WIDTH))

BLOCK_SIZE = GAME_FIELD_WIDTH / MAP_WIDTH

PLAYER_SPEED = (BLOCK_SIZE / 5.5) * OLD_FPS
PLAYER_JUMP_FORCE = (BLOCK_SIZE / 4) * OLD_FPS
PLAYER_MAX_VELOCITY_Y = 75.0 * OLD_FPS
PLAYER_DASH_SPEED = (BLOCK_SIZE * 2) * OLD_FPS
PLAYER_DASH_DURATION = 50  # milliseconds
PLAYER_HEALTH = 100

MAX_ANTI_GRAVITY = (BLOCK_SIZE / 700) * OLD_FPS
CHANGE_ANTI_GRAVITY = 0.03 * OLD_FPS
ANTI_GRAVITY_DECAY = (BLOCK_SIZE / 15000) * OLD_FPS

GRAVITY = (BLOCK_SIZE / 1.15) * OLD_FPS

# Game consts / Bullets
BIG_BULLET_WIDTH = BLOCK_SIZE / 2
BIG_BULLET_HEIGHT = BLOCK_SIZE / 3
BIG_BULLET_SPEED = (BLOCK_SIZE / 3.0) * OLD_FPS
BIG_BULLET_MAX_DISTANCE = GAME_FIELD_WIDTH * 2
BIG_BULLET_DAMAGE = 100

SMALL_BULLET_WIDTH = BLOCK_SIZE / 3
SMALL_BULLET_HEIGHT = BLOCK_SIZE / 4.5
SMALL_BULLET_SPEED = (BLOCK_SIZE / 2) * OLD_FPS
SMALL_BULLET_MAX_DISTANCE = GAME_FIELD_WIDTH * 1
SMALL_BULLET_DAMAGE = 34

MACHINE_GUN_COOLDOWN = 350
MACHINE_GUN_BULLET_WIDTH = BLOCK_SIZE / 3
MACHINE_GUN_BULLET_HEIGHT = BLOCK_SIZE / 4.5
MACHINE_GUN_BULLET_SPEED = (BLOCK_SIZE / 2) * OLD_FPS
MACHINE_GUN_BULLET_DAMAGE = 20

LASER_GUN_COOLDOWN = 1250
LASER_GUN_BULLET_HEIGHT = BLOCK_SIZE / 10
LASER_GUN_BULLET_DAMAGE = 34

BAZOOKA_COOLDOWN = 1000
BAZOOKA_BULLET_WIDTH = BLOCK_SIZE / 2
BAZOOKA_BULLET_HEIGHT = BLOCK_SIZE / 3
BAZOOKA_BULLET_SPEED = (BLOCK_SIZE / 5) * OLD_FPS
BAZOOKA_BULLET_DAMAGE = 100

SHOTGUN_COOLDOWN = 750
SHOTGUN_BULLET_WIDTH = BLOCK_SIZE / 4
SHOTGUN_BULLET_HEIGHT = BLOCK_SIZE / 5
BULLET_SPEED_DIVIDER = 2.5
SHOTGUN_BULLET_SPEED = (BLOCK_SIZE / BULLET_SPEED_DIVIDER) * OLD_FPS
SHOTGUN_BULLET_DISPERSION_VELOCITY = BULLET_SPEED_DIVIDER * 14
SHOTGUN_BULLET_DAMAGE = 11.4


# UI / Text & Buttons sizes
BUTTON_WIDTH = GAME_FIELD_WIDTH / 6
BUTTON_HEIGHT = GAME_FIELD_HEIGHT / 20
BUTTON_OFFSET = BUTTON_HEIGHT / 3

SCORES_WIDTH = BLOCK_SIZE
SCORES_HEIGHT = GAME_FIELD_HEIGHT / 25

VICTORY_TEXT_WIDTH = GAME_FIELD_WIDTH / 3
VICTORY_TEXT_HEIGHT = GAME_FIELD_HEIGHT / 7.5


# Colors
RED = (209 / 255, 17 / 255, 17 / 255, 1.0)
GREEN = (39 / 255, 173 / 255, 16 / 255, 1.0)
BLUE = (10 / 255, 22 / 255, 247 / 255, 1.0)
ORANGE = (227 / 255, 138 / 255, 14 / 255, 1.0)
WHITE = (1, 1, 1, 1.0)
DARK_GREY = (0.2, 0.2, 0.2, 1.0)
GREY = (0.21, 0.21, 0.21, 1.0)
GREY_2 = (0.3, 0.3, 0.3, 1.0)
GAME_BG_COLOR = (120 / 255, 120 / 255, 120 / 255, 1.0)
MENU_BG_COLOR = (0.1, 0.1, 0.1, 1.0)
