import ctypes


def get_screen_resolution() -> tuple[float, float]:
    ctypes.windll.user32.SetProcessDPIAware()
    width = ctypes.windll.user32.GetSystemMetrics(0)
    height = ctypes.windll.user32.GetSystemMetrics(1)
    return width, height


CURRENT_SCREEN_SIZE = get_screen_resolution()
GAME_FIELD_PROPORTIONS = float(16 / 9)

SCREEN_WIDTH = CURRENT_SCREEN_SIZE[0] * 0.8
SCREEN_HEIGHT = SCREEN_WIDTH / GAME_FIELD_PROPORTIONS

GAME_FIELD_WIDTH = SCREEN_WIDTH
GAME_FIELD_HEIGHT = GAME_FIELD_WIDTH / GAME_FIELD_PROPORTIONS


# Game consts
MENU_FPS = 60

UPDATE_FPS = 120
DRAW_FPS = 60

UPDATE_DT = 1.0 / UPDATE_FPS
DRAW_DT = 1.0 / DRAW_FPS

OLD_FPS = 120

BLOCK_SIZE = GAME_FIELD_WIDTH / 41

PLAYER_SPEED = (BLOCK_SIZE / 5.5) * OLD_FPS
PLAYER_JUMP_FORCE = (BLOCK_SIZE / 4) * OLD_FPS
PLAYER_MAX_VELOCITY_Y = 75.0 * OLD_FPS
PLAYER_HEALTH = 100

BIG_BULLET_WIDTH = BLOCK_SIZE / 2
BIG_BULLET_HEIGHT = BLOCK_SIZE / 3
BIG_BULLET_SPEED = (BLOCK_SIZE / 3.0) * OLD_FPS
BIG_BULLET_MAX_DISTANCE = GAME_FIELD_WIDTH * 2
BIG_BULLET_DAMAGE = 100

SMALL_BULLET_WIDTH = BLOCK_SIZE / 3
SMALL_BULLET_HEIGHT = BLOCK_SIZE / 4.5
SMALL_BULLET_SPEED = (BLOCK_SIZE / 2) * OLD_FPS
SMALL_BULLET_MAX_DISTANCE = GAME_FIELD_WIDTH * 1
SMALL_BULLET_DAMAGE = 34

MAX_ANTI_GRAVITY = (BLOCK_SIZE / 700) * OLD_FPS
CHANGE_ANTI_GRAVITY = 0.03 * OLD_FPS
ANTI_GRAVITY_DECAY = (BLOCK_SIZE / 15000) * OLD_FPS

GRAVITY = (BLOCK_SIZE / 1.15) * OLD_FPS

IS_DEBUG = False

# Other

BUTTON_WIDTH = GAME_FIELD_WIDTH / 6
BUTTON_HEIGHT = GAME_FIELD_HEIGHT / 20
BUTTON_OFFSET = BUTTON_HEIGHT / 3

SCORES_WIDTH = BLOCK_SIZE
SCORES_HEIGHT = GAME_FIELD_HEIGHT / 25

VICTORY_TEXT_WIDTH = GAME_FIELD_WIDTH / 3
VICTORY_TEXT_HEIGHT = GAME_FIELD_HEIGHT / 7.5


# Colors
RED = (209 / 255, 17 / 255, 17 / 255, 1.0)
GREEN = (39 / 255, 173 / 255, 16 / 255, 1.0)
BLUE = (10 / 255, 22 / 255, 247 / 255, 1.0)
ORANGE = (227 / 255, 138 / 255, 14 / 255, 1.0)
WHITE = (1, 1, 1, 1.0)
DARK_GREY = (0.2, 0.2, 0.2, 1.0)
GREY = (0.21, 0.21, 0.21, 1.0)
GREY_2 = (0.3, 0.3, 0.3, 1.0)
BG_COLOR = (120 / 255, 120 / 255, 120 / 255, 1.0)
