import pygame

pygame.init()

GAME_FIELD_PROPORTIONS = float(16 / 9)
GAME_FIELD_WIDTH = pygame.display.Info().current_w * 0.8 + 2.0
GAME_FIELD_HEIGHT = GAME_FIELD_WIDTH / GAME_FIELD_PROPORTIONS

FPS = 300

PLAYER_SPEED = 3.5
PLAYER_JUMP_FORCE = 5.0
PLAYER_MAX_ANTI_GRAVITY = 0.04
PLAYER_CHANGE_ANTI_GRAVITY = 0.01

ENEMY_SPEED = 1.7

GRAVITY = 0.12
BLOCK_SIZE = 30.0

IS_DEBUG = True

# Colors
RED = (1, 0, 0)
GREEN = (0, 1, 0)
BLUE = (0, 0, 1)
ORANGE = (1, 0.5, 0)
YELLOW = (1, 1, 0)
DARK_GREY = (0.2, 0.2, 0.2)
